# Generated by Django 5.2 on 2025-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='cargo',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='contrasena',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
