# Generated by Django 5.2 on 2025-06-30 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Denuncias', '0002_rename_ubicacion_denuncia_referencia_and_more'),
        ('Funcionarios', '0002_rename_cargo_funcionario_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Denuncias.denuncia')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Funcionarios.funcionario')),
            ],
        ),
    ]
