# Generated by Django 5.2 on 2025-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='ubicacion',
            new_name='referencia',
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='titulo',
            new_name='tipo_denuncia',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
